---
title: "Titanic March 2015"
author: "George Fisher"
date: "Wednesday, March 18, 2015"
output: html_document
---
Read and clean the data

```{r setup,message=FALSE}
setwd("~/Dropbox/kaggle/Classification Titanic/March2015")
opar = par(no.readonly=TRUE)

source("clean_the_dataset.R")

# dummyvars = FALSE => factors
# dummyvars = TRUE  => dummy variables/indicators
# NOTE: dummy vars made boost and rf worse
# ----------------------------------------
dummyvars = FALSE
output = clean_the_dataset(read.csv("train.csv",
                                      strip.white=TRUE,
                                      stringsAsFactors=FALSE),
                           dummy.vars=dummyvars)
raw_data = output$all
X        = output$X
Y        = output$Y
YX       = output$YX
rm(output)
str(raw_data)
```
Select training indices, formula and threshold
```{r testset}
set.seed(1009)
formla    = formula(Survived~.-PassengerId)
threshold = 0.57

smp_size  <- floor(0.25 * nrow(raw_data))
test.set  <- sample(seq_len(nrow(raw_data)), size = smp_size)
```

Predictions
```{r predictions,message=FALSE,warning=FALSE}


source("rpart.R")#,echo=TRUE)
#source("logit.R")
#source("svm.R")
#source("qda.R")
source("boost.R")
source("boostTest.R")
#source("rf.R")
#source("cforest.R")
#source("exhaust.R")
source("ridge.R")

bymse = comparison[,order(comparison[4,],decreasing=FALSE)]
byacc = bymse[,order(bymse[1,],decreasing=TRUE)]
print(byacc)
```  
Get the cleaned test data set
---------------------------   
```{r gettest}
output.test = clean_the_dataset(read.csv("test.csv",
                                      strip.white=TRUE,
                                      stringsAsFactors=FALSE),
                                dummy.vars=dummyvars)
Xtest = output.test$Xtest
```   

Apply BOOST to the **full training dataset** with the best-accuracy parameters
--------------   
```{r rfapply}
submission.fit = gbm(Survived~.-PassengerId, data=raw_data,
                     distribution="bernoulli", 
                     n.trees=5794, 
                     interaction.depth=1,
                     shrinkage=0.001)
```
Predict the test set
-----------   
```{r rftest}

submission.pred = predict (submission.fit, 
                           newdata=Xtest,
                           n.trees=5794,
                           type="response")

submission.df = data.frame(PassengerId=Xtest$PassengerId,
                           Survived=as.numeric(submission.pred>0.54))

print(submission.df[1:10,])

write.csv(submission.df,file="submission_boost_bestACCURACY.csv",row.names=FALSE)
```